import test from'node:test';import assert from'node:assert/strict';import{ApiError,assertAllowedFields,mapDatabaseError}from'../server/http';import{ensureAttendanceStatus,ensureDate,ensureHomeworkStatus,ensureNumber,ensureReportTransition,ensureUuid,reportTransitions}from'../server/validators';import{pagination,sort}from'../server/query';import{validateStorageTarget}from'../server/storage';import{students,guardians,subjects,classes,attendance,homework,assessments,reports,calendar}from'../server/payloads';import{sendEmail}from'../services/email';import{sendSMS}from'../services/sms';import{generateReportPDF}from'../services/pdf';
const uuid='550e8400-e29b-41d4-a716-446655440001';
test('all major resources define explicit write allowlists',()=>{for(const r of[students,guardians,subjects,classes,attendance,homework,assessments,reports,calendar])assert.ok(r.writeFields.length>0)});
test('student payload rejects missing fields',()=>assert.throws(()=>students.create({},uuid),ApiError));
test('student create ignores caller identity and validates values',()=>assert.equal(students.create({first_name:'A',last_name:'B',student_id:'S1'},uuid).student_id,'S1'));
test('attendance validates status',()=>assert.throws(()=>ensureAttendanceStatus('Unknown'),ApiError));
test('homework validates submission status',()=>assert.throws(()=>ensureHomeworkStatus('Done'),ApiError));
test('scores reject negative and non-number values',()=>{assert.throws(()=>ensureNumber(-1,'score',0),ApiError);assert.throws(()=>ensureNumber('4','score',0),ApiError)});
test('dates require stable date-only format',()=>{assert.equal(ensureDate('2026-09-02','date'),'2026-09-02');assert.throws(()=>ensureDate('tomorrow','date'),ApiError)});
test('UUID validation rejects ID tampering strings',()=>{for(const x of['../x','not-a-uuid','','550e8400-e29b-41d4-a716'])assert.throws(()=>ensureUuid(x),ApiError)});
test('report transition table contains intended workflow',()=>assert.deepEqual(reportTransitions['Under Review'],['Changes Requested','Approved']));
test('report transition accepts Draft to Submitted',()=>assert.equal(ensureReportTransition('Draft','Submitted'),'Submitted'));
test('report transition rejects Draft to Approved',()=>assert.throws(()=>ensureReportTransition('Draft','Approved'),ApiError));
test('report transition rejects changes after Sent',()=>assert.throws(()=>ensureReportTransition('Sent','Submitted'),ApiError));
test('unexpected mass-assignment fields are rejected',()=>assert.throws(()=>assertAllowedFields({role:'admin'},['name']),ApiError));
test('unique database violations map to safe 409',()=>assert.throws(()=>mapDatabaseError({code:'23505',message:'private'}),(e:any)=>e.status===409&&!e.message.includes('private')));
test('foreign-key violations map to safe 409',()=>assert.throws(()=>mapDatabaseError({code:'23503'}),(e:any)=>e.status===409));
test('RLS violations map to safe 403',()=>assert.throws(()=>mapDatabaseError({code:'42501'}),(e:any)=>e.status===403));
test('storage allows student UUID convention',()=>assert.deepEqual(validateStorageTarget('documents',`students/${uuid}/file.pdf`),{bucket:'documents',path:`students/${uuid}/file.pdf`}));
test('storage allows class and report conventions',()=>{validateStorageTarget('homework-files',`classes/${uuid}/x`);validateStorageTarget('report-pdfs',`reports/${uuid}/x`)});
test('storage rejects unsupported bucket',()=>assert.throws(()=>validateStorageTarget('public',`students/${uuid}/x`),ApiError));
test('storage rejects traversal and malformed UUID paths',()=>{assert.throws(()=>validateStorageTarget('documents',`students/${uuid}/../x`),ApiError);assert.throws(()=>validateStorageTarget('documents','students/not-a-uuid/x'),ApiError)});
test('pagination defaults to 25 and has a 100 maximum',()=>{const r={nextUrl:new URL('http://x')}as any;assert.equal(pagination(r).limit,25);assert.throws(()=>pagination({nextUrl:new URL('http://x?limit=101')}as any),ApiError)});
test('sorting uses allowlisted columns',()=>{assert.equal(sort({nextUrl:new URL('http://x?sort=name')}as any,{name:'last_name'},'name').column,'last_name');assert.throws(()=>sort({nextUrl:new URL('http://x?sort=sql')}as any,{name:'name'},'name'),ApiError)});
test('mock email adapter returns safe provider metadata',async()=>assert.equal((await sendEmail({to:'a@example.com',subject:'x'})).provider,'mock'));
test('mock SMS adapter validates recipient',async()=>await assert.rejects(()=>sendSMS({to:'bad',message:'x'})));
test('PDF adapter returns binary content without route coupling',async()=>assert.ok((await generateReportPDF({id:uuid,report_period:'T1',status:'Draft'})).content instanceof Uint8Array));
