import type { NextRequest } from 'next/server';
export class ApiError extends Error{constructor(public status:number,public code:string,message:string){super(message)}}
export const ok=(data:unknown,status=200,meta?:unknown)=>Response.json(meta?{data,meta}:{data},{status});
export const noContent=()=>new Response(null,{status:204});
export function mapDatabaseError(error:{code?:string;message?:string}|null){if(!error)return;if(error.code==='23505')throw new ApiError(409,'CONFLICT','The record already exists.');if(error.code==='23503')throw new ApiError(409,'RELATIONSHIP_CONFLICT','The record is referenced or has an invalid relationship.');if(error.code==='22P02'||error.code==='22007')throw new ApiError(400,'INVALID_INPUT','A supplied value is invalid.');if(error.code==='PGRST116')throw new ApiError(404,'NOT_FOUND','The requested record was not found.');if(error.code==='42501')throw new ApiError(403,'FORBIDDEN','Access is not permitted.');throw new ApiError(500,'DATABASE_ERROR','The request could not be completed.');}
export function errorResponse(error:unknown){if(error instanceof ApiError)return Response.json({error:{code:error.code,message:error.message}},{status:error.status});console.error('API request failed',error instanceof Error?error.message:'unknown error');return Response.json({error:{code:'INTERNAL_ERROR',message:'The request could not be completed.'}},{status:500});}
export function route<T extends unknown[]>(handler:(request:NextRequest,...args:T)=>Promise<Response>){return async(request:NextRequest,...args:T)=>{try{return await handler(request,...args)}catch(error){return errorResponse(error)}}}
export async function jsonBody(request:NextRequest):Promise<Record<string,unknown>>{try{const value=await request.json();if(!value||typeof value!=='object'||Array.isArray(value))throw new Error();return value}catch{throw new ApiError(400,'INVALID_JSON','A JSON object body is required.')}}
export function assertAllowedFields(body:Record<string,unknown>,allowed:readonly string[]){const unexpected=Object.keys(body).filter(k=>!allowed.includes(k));if(unexpected.length)throw new ApiError(400,'UNEXPECTED_FIELD',`Unexpected field: ${unexpected[0]}.`)}
