import type{NextRequest}from'next/server';import{requireAdmin,requireRole}from'./auth';import{ApiError,assertAllowedFields,jsonBody,noContent,ok,route}from'./http';import{many,mapDatabaseError,mutate,one}from'./resource-utils';import{pagination,pageMeta,sort}from'./query';import{ensureUuid}from'./validators';
export type ResourceConfig={table:string;select?:string;writeFields:readonly string[];create:(b:Record<string,unknown>,profileId:string)=>Record<string,unknown>;patch:(b:Record<string,unknown>,current?:any)=>Record<string,unknown>;filters?:readonly string[];searchColumns?:readonly string[];sorts?:Record<string,string>;defaultSort?:string;dateColumn?:string;adminWrite?:boolean;deleteMode?:'delete'|'archive'|'deactivate'|'none'};
async function context(request:NextRequest,admin=false){return admin?requireAdmin(request):requireRole(request,['admin','teacher'])}
export function collectionHandlers(config:ResourceConfig,admin=false){return{
 GET:route(async request=>{const c=await context(request,admin),p=pagination(request),s=sort(request,config.sorts||{created_at:'created_at'},config.defaultSort||'created_at');let q:any=c.supabase.from(config.table).select(config.select||'*',{count:'exact'});for(const f of config.filters||[]){const v=request.nextUrl.searchParams.get(f);if(v!==null)q=q.eq(f,v)}if(config.dateColumn){const from=request.nextUrl.searchParams.get('date_from'),to=request.nextUrl.searchParams.get('date_to');if(from)q=q.gte(config.dateColumn,from);if(to)q=q.lte(config.dateColumn,to)}if(config.table==='students'){const classId=request.nextUrl.searchParams.get('class_id');if(classId){ensureUuid(classId,'class_id');const rel=await many(c.supabase.from('class_students').select('student_id').eq('class_id',classId));q=q.in('id',rel.data.map(x=>x.student_id))}}const search=request.nextUrl.searchParams.get('search');if(search&&config.searchColumns?.length){const safe=search.replace(/[%(),]/g,'');q=q.or(config.searchColumns.map(x=>`${x}.ilike.%${safe}%`).join(','))}const r=await many(q.order(s.column,{ascending:s.ascending}).range(p.from,p.to));return ok(r.data,200,{pagination:pageMeta(p.page,p.limit,r.count)})}),
 POST:route(async request=>{const c=await context(request,admin||config.adminWrite),body=await jsonBody(request);assertAllowedFields(body,config.writeFields);const data=await mutate(c.supabase.from(config.table).insert(config.create(body,c.profile.id)).select().single());return ok(data,201)})}}
export function itemHandlers(config:ResourceConfig,admin=false){return{
 GET:route(async(request,_:{params:{id:string}})=>{ensureUuid(_.params.id);const c=await context(request,admin),data=await one(c.supabase.from(config.table).select(config.select||'*').eq('id',_.params.id).maybeSingle());return ok(data)}),
 PATCH:route(async(request,_:{params:{id:string}})=>{ensureUuid(_.params.id);const c=await context(request,admin||config.adminWrite),body=await jsonBody(request);assertAllowedFields(body,config.writeFields);let current:any;if(config.table==='student_reports')current=await one(c.supabase.from(config.table).select('*').eq('id',_.params.id).maybeSingle());const payload=config.patch(body,current);if(!Object.keys(payload).length)throw new ApiError(400,'VALIDATION_ERROR','No update fields were supplied.');const data=await mutate(c.supabase.from(config.table).update(payload).eq('id',_.params.id).select().maybeSingle());if(!data)throw new ApiError(404,'NOT_FOUND','The requested record was not found.');return ok(data)}),
 DELETE:route(async(request,_:{params:{id:string}})=>{ensureUuid(_.params.id);const c=await context(request,admin||config.adminWrite);if(config.deleteMode==='none')throw new ApiError(405,'METHOD_NOT_ALLOWED','This record cannot be deleted.');let q:any=c.supabase.from(config.table);if(config.deleteMode==='archive')q=q.update({status:'archived'});else if(config.deleteMode==='deactivate')q=q.update({active:false});else q=q.delete();const{data,error}=await q.eq('id',_.params.id).select();mapDatabaseError(error);if(!data?.length)throw new ApiError(404,'NOT_FOUND','The requested record was not found.');return noContent()})}}
