'use client';
import{ChevronDown,ChevronLeft,ChevronRight,Search,X}from'lucide-react';
export function Avatar({name,size='md'}){return <span className={`avatar avatar-${size}`}>{name.split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('')}</span>}
export function Badge({children,tone}){const key=tone||String(children).toLowerCase().replaceAll(' ','-');return <span className={`badge badge-${key}`}>{children}</span>}
export function PageHeader({title,description,action,onAction}){return <div className="page-heading"><div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<button className="btn btn-primary" onClick={onAction}>{action}</button>}</div>}
export function SearchBox({value,onChange,placeholder='Search…'}){return <label className="search-box"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
export function Modal({open,title,children,onClose,footer}){if(!open)return null;return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Close"><X size={19}/></button></header><div className="modal-body">{children}</div>{footer&&<footer>{footer}</footer>}</section></div>}
export function FormField({label,children,required}){return <label className="form-field"><span>{label}{required&&<b> *</b>}</span>{children}</label>}
export function Tabs({items,active,onChange}){return <div className="tabs">{items.map(x=><button key={x} className={active===x?'active':''} onClick={()=>onChange(x)}>{x}</button>)}</div>}
export function EmptyState({title='Nothing here yet',text='New records will appear here.'}){return <div className="empty-state"><h3>{title}</h3><p>{text}</p></div>}
export function Pagination({meta,onPage}){if(!meta||meta.total_pages<=1)return null;const start=(meta.page-1)*meta.limit+1,end=Math.min(meta.page*meta.limit,meta.total);return <div className="pagination"><span>Showing {start}–{end} of {meta.total}</span><div><button disabled={meta.page<=1} onClick={()=>onPage(meta.page-1)} aria-label="Previous"><ChevronLeft size={16}/></button>{Array.from({length:Math.min(meta.total_pages,5)},(_,i)=>i+1).map(page=><button key={page} className={page===meta.page?'active':''} onClick={()=>onPage(page)}>{page}</button>)}<button disabled={meta.page>=meta.total_pages} onClick={()=>onPage(meta.page+1)} aria-label="Next"><ChevronRight size={16}/></button></div></div>}
export function ActionMenu({onAction}){return <details className="action-menu"><summary aria-label="Actions">•••</summary><div><button onClick={()=>onAction('View')}>View details</button><button onClick={()=>onAction('Edit')}>Edit</button><button className="danger" onClick={()=>onAction('Archive')}>Archive</button></div></details>}
export function DataTable({columns,rows,onRow,onAction}){return <div className="table-wrap"><table className="table"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}{onAction&&<th aria-label="Actions"/>}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||row.name||i} className={onRow?'clickable':''} onClick={()=>onRow?.(row)}>{columns.map(c=><td key={c.key}>{c.render?c.render(row):row[c.key]}</td>)}{onAction&&<td onClick={e=>e.stopPropagation()}><ActionMenu onAction={a=>onAction(a,row)}/></td>}</tr>)}</tbody></table></div>}
export function Select({value,onChange,children,label}){return <label className="select-control">{label&&<span>{label}</span>}<select value={value} onChange={e=>onChange(e.target.value)}>{children}</select><ChevronDown size={15}/></label>}
