import type{NextRequest}from'next/server';import{createSupabaseAdminClient,requireAdmin}from'@/server/auth';import{ApiError,jsonBody,ok,route}from'@/server/http';import{mapDatabaseError}from'@/server/resource-utils';import{ensureDate,ensureUuid}from'@/server/validators';
// A register is every attendance row for one class on one date.
const formatDay=(date:string)=>new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${date}T00:00:00Z`));
// Request: notify the class's teachers to fill in a register that is missing or incomplete.
export const POST=route(async(r:NextRequest)=>{await requireAdmin(r);const b=await jsonBody(r),classId=ensureUuid(b.class_id,'class_id'),date=ensureDate(b.attendance_date,'attendance_date');const admin=createSupabaseAdminClient();const{data:cls,error:classError}=await admin.from('classes').select('id,name').eq('id',classId).maybeSingle();mapDatabaseError(classError);if(!cls)throw new ApiError(404,'NOT_FOUND','The class was not found.');const[{count:enrolled,error:enrolledError},{count:marked,error:markedError}]=await Promise.all([admin.from('class_students').select('id',{count:'exact',head:true}).eq('class_id',classId),admin.from('attendance').select('id',{count:'exact',head:true}).eq('class_id',classId).eq('attendance_date',date)]);mapDatabaseError(enrolledError);mapDatabaseError(markedError);if(enrolled&&(marked??0)>=enrolled)throw new ApiError(409,'REGISTER_COMPLETE','This register has already been filled in.');const{data:links,error:linkError}=await admin.from('class_teachers').select('teachers(profiles(id,role,active))').eq('class_id',classId);mapDatabaseError(linkError);const teacherIds=[...new Set((links??[]).map((l:any)=>l.teachers?.profiles).filter((p:any)=>p?.active&&p.role==='teacher').map((p:any)=>p.id as string))];if(!teacherIds.length)throw new ApiError(409,'NO_TEACHER','No active teacher is assigned to this class. Assign a teacher first.');const{error}=await admin.from('notifications').insert(teacherIds.map(user_id=>({user_id,title:'Register requested',message:`Please fill in the ${cls.name} register for ${formatDay(date)}.`,type:'attendance',link:`attendance?class_id=${classId}&date=${date}`})));mapDatabaseError(error);return ok({notified:teacherIds.length},201)});
// Delete: remove every attendance mark for the class on that date.
export const DELETE=route(async(r:NextRequest)=>{await requireAdmin(r);const q=r.nextUrl.searchParams,classId=ensureUuid(q.get('class_id'),'class_id'),date=ensureDate(q.get('date'),'date');const{count,error}=await createSupabaseAdminClient().from('attendance').delete({count:'exact'}).eq('class_id',classId).eq('attendance_date',date);mapDatabaseError(error);return ok({deleted:count??0})});

export const dynamic='force-dynamic';
